/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BabySitterChargingApp;

public class App {
  
    public static void main(String[] args) {
        ShiftGenerator shift = new ShiftGenerator();
		shift.generateShift();
		System.out.println("Thank you for hiring me!");    }
}
