/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package babySitterChargingApp;

public class App {
  
    public static void main(String[] args) {
        shiftGenerator shift = new shiftGenerator();
		shift.generateShift();
		System.out.println("Thank you for hiring me!");    }
}
