package BabySitterChargingApp;
// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package babySitterChargingApp;

// import org.junit.Test;
// import static org.junit.Assert.*;

// // public class AppTest {
// //     @Test public void testAppHasAGreeting() {
// //         App classUnderTest = new App();
// //         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
// //     }

//     // need tests especially for user input validation as the time factor is difficult

//     // need tests for the time objs and hours

//     // need tests for the generation of shift windows

//     // need tests for calculating charge fee and displayin back to user
// }
